/** Declaration file generated by dts-gen */

export = byu_jwt;

declare function byu_jwt(options: any): any;

declare namespace byu_jwt {
  const BYU_JWT_HEADER_CURRENT: string

  const BYU_JWT_HEADER_ORIGINAL: string

  const WELL_KNOWN_URL: string

  function authenticate(headers): Promise<> {}

  function authenticateUAPIMiddleware(headers): Promise<> {}

  function decodeJWT(headers): Promise<> {}

  function getOpenIdConfiguration(headers): Promise<> {}

  function getPublicKey(headers): Promise<> {}

  function verifyJWT(headers): Promise<> {}

  function AuthenticationError(message: any, error: any): void;

  function JsonWebTokenError(message: any, error: any): void;

  function NotBeforeError(message: any, date: any): void;

  function TokenExpiredError(message: any, expiredAt: any): void;
}

